### ISSUE TITLE
[Tempad with shaders] Please update this mod to 1.20.1.

### ISSUE THREAD

**Issue by luanwolf** [Bawnorton/NortonsOddities#2]
I would really like your mod [Tempad with shaders](https://www.curseforge.com/minecraft/mc-mods/tempad-with-shaders) to be updated to 1.20.1... I tried several ways to run the Tempad mod with shaders in the current versions, but it was not possible, and I learned about your mod.

I apologize for the previous issue.

Thanks 😊

**Comment by Bawnorton** [comment]
I'll look into it when I get home from vacation ~5 days

**Comment by luanwolf** [comment]
Ohhh, I would appreciate it.

Enjoy your vacation.

**Comment by Bawnorton** [comment]
Released, it'll be on CF shorlty.

**Comment by luanwolf** [comment]
Thaaaaaaaaaaaaaanks <3
